image: python:3.7-alpine3.7

before_script:
  - pip install --upgrade pip && pip install \
    mkdocs \
    mkdocs-material \
    python-markdown-math \
    pygments \
    prompt-toolkit

pages:
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
    - public
  only:
  - master
